

export enum MenuMode {
  NONE = 'NONE',
  ACCOUNT = 'ACCOUNT',
  SEARCH = 'SEARCH',
  NOTIFICATIONS = 'NOTIFICATIONS',
  GRAPHS = 'GRAPHS',
  CONTACTS = 'CONTACTS',
  MAP = 'MAP',
  FEED = 'FEED',
  ABOUT = 'ABOUT',
}